# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2

updates:
  - package-ecosystem: github-actions
    directory: / # scans workflows + actions
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Amsterdam
    labels: [dependencies, github-actions]
    # assignees: [mgm-sec]
    commit-message:
      prefix: "deps(actions)"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directories: ["/"]
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Amsterdam
    labels: [dependencies, docker]
    # assignees: [mgm-sec]
    commit-message:
      prefix: "deps(docker)"
    open-pull-requests-limit: 5
    groups:
      docker-patch-minor:
        update-types: [patch, minor]
        patterns: ["*"]

  - package-ecosystem: composer
    directory: / # composer.json + composer.lock in the root
    schedule:
      interval: weekly
      day: monday
      time: "05:45"
      timezone: Europe/Amsterdam
    labels: [dependencies, php]
    # assignees: [mgm-sec]
    commit-message:
      prefix: "deps(php)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
      semver-major-days: 14
    groups:
      php-patch-minor:
        update-types: [patch, minor]
        patterns: ["*"]
